package api.infrastructure.env.enums

enum class EnvKey(val key: String) {
    APPLICATION_ENVIRONMENT("APPLICATION_ENVIRONMENT"),

    API_HOST("API_HOST"),
    API_PORT("API_PORT"),

    DATABASE_HOST("DATABASE_HOST"),
    DATABASE_PORT("DATABASE_PORT"),
    DATABASE_NAME("DATABASE_NAME"),
    DATABASE_USER("DATABASE_USER"),
    DATABASE_PASSWORD("DATABASE_PASSWORD"),

    JWT_SECRET("JWT_SECRET"),
    JWT_ACCESS_EXPIRATION("JWT_ACCESS_EXPIRATION"),
    JWT_REFRESH_EXPIRATION("JWT_REFRESH_EXPIRATION"),

    S3_BUCKET_NAME("S3_BUCKET_NAME"),
    S3_REGION("S3_REGION"),
    S3_ACCESS_KEY("S3_ACCESS_KEY"),
    S3_SECRET_KEY("S3_SECRET_KEY"),
    S3_ENDPOINT_URL("S3_ENDPOINT_URL"),
    S3_ENDPOINT_PORT("S3_ENDPOINT_PORT"),
}